# Generated by Django 6.0.1 on 2026-02-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProposicaoRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=100, unique=True)),
                ('raw', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
