# Generated by Django 6.0.1 on 2026-03-26 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0002_tramitacaosettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('last_processed', models.DateTimeField(auto_now_add=True, null=True)),
                ('desactivated', models.BooleanField(default=False)),
                ('desactivated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('erro_messagem', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('desactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MateriaHTML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_cmf', models.CharField(max_length=50, unique=True)),
                ('html', models.FileField(upload_to='materia')),
                ('arquivo_html', models.FileField(upload_to='materias_brutas/%Y/%m/%d/')),
                ('processado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.materiasettings')),
            ],
        ),
        migrations.DeleteModel(
            name='TramitacaoSettings',
        ),
    ]
