# Generated by Django 6.0.1 on 2026-03-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0003_materiasettings_materiahtml_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiasettings',
            name='save_html',
            field=models.BooleanField(default=True),
        ),
    ]
