# Generated by Django 6.0.1 on 2026-03-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0004_materiasettings_save_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiasettings',
            name='camara_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='materiasettings',
            name='desactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materiasettings',
            name='last_processed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
