# Generated by Django 6.0.1 on 2026-03-26 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0005_materiasettings_camara_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiahtml',
            name='html',
        ),
    ]
