# Generated by Django 6.0.1 on 2026-03-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0006_remove_materiahtml_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiahtml',
            name='arquivo_html',
            field=models.FileField(upload_to='materias_brutas/%Y/%m/%d/%H/'),
        ),
        migrations.AlterField(
            model_name='materiasettings',
            name='save_html',
            field=models.BooleanField(default=False),
        ),
    ]
