# Generated by Django 6.0.1 on 2026-03-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camara', '0002_vereador_funcao_vereador_imagem_vereador_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='vereador',
            name='camara_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
