# Generated by Django 6.0.1 on 2026-03-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camara', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vereador',
            name='funcao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vereador',
            name='imagem',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vereador',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
