# Generated by Django 6.0.1 on 2026-03-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camara', '0003_vereador_camara_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vereador',
            name='data_desativacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
