# Generated by Django 6.0.1 on 2026-04-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camara', '0004_vereador_data_desativacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='sigla',
            field=models.CharField(max_length=50),
        ),
    ]
