# Generated by Django 6.0.1 on 2026-03-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camaratoken',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
