# Generated by Django 6.0.1 on 2026-03-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_camaratoken_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_type', models.CharField(choices=[('danger', 'Alerta'), ('warning', 'Aviso'), ('info', 'Informativo'), ('success', 'Sucesso')], max_length=20, verbose_name='Tipo de Webhook')),
                ('url', models.URLField(help_text='URL completa do webhook do Discord', max_length=255, verbose_name='URL do Webhook')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Webhook do Discord',
                'verbose_name_plural': 'Webhooks do Discord',
                'ordering': ['webhook_type'],
            },
        ),
    ]
