# Generated by Django 6.0.1 on 2026-03-24 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_discordwebhook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discordwebhook',
            options={'verbose_name': 'Webhook do Discord', 'verbose_name_plural': 'Webhooks do Discord'},
        ),
        migrations.RemoveField(
            model_name='discordwebhook',
            name='webhook_type',
        ),
    ]
