# Generated by Django 6.0.1 on 2026-03-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_alter_discordwebhook_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordwebhook',
            name='dev',
            field=models.BooleanField(default=False, verbose_name='Desenvolvimento'),
        ),
    ]
