# Generated by Django 6.0.1 on 2026-04-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_discordwebhook_dev'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheetsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials', models.FileField(help_text='Arquivo JSON da Service Account do Google. Armazenado criptografado.', upload_to='files/credentials', verbose_name='Credenciais (JSON)')),
                ('spreadsheet_name', models.CharField(help_text='Nome exato da planilha no Google Drive.', max_length=255, verbose_name='Nome da Planilha')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Configuração do Google Sheets',
                'verbose_name_plural': 'Configurações do Google Sheets',
            },
        ),
    ]
