# Generated by Django 6.0.1 on 2026-04-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_googlesheetsconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=255)),
                ('service', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Gemini')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Chave de API',
                'verbose_name_plural': 'Chaves de API',
            },
        ),
    ]
