# Generated by Django 6.0.1 on 2026-04-28 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_apikeys'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.JSONField(default=list)),
                ('response', models.JSONField(default=list)),
                ('tokens_prompt', models.IntegerField(default=0)),
                ('tokens_response', models.IntegerField(default=0)),
                ('tokens_total', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to='integrations.apikeys')),
            ],
            options={
                'verbose_name': 'Uso de IA',
                'verbose_name_plural': 'Usos de IA',
            },
        ),
    ]
