# Generated by Django 6.0.1 on 2026-04-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_aiusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlesheetsconfig',
            name='worksheet_name',
            field=models.CharField(blank=True, help_text='Nome exato da tabela no Google Sheets.', max_length=255, null=True, verbose_name='Nome da tabela'),
        ),
    ]
