# Generated by Django 6.0.1 on 2026-02-03 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Proposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=80)),
                ('ementa', models.TextField(blank=True)),
                ('descricao', models.TextField(blank=True)),
                ('data_apresentacao', models.DateField(blank=True, null=True)),
                ('situacao', models.CharField(blank=True, max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('link_externo', models.URLField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('autoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legis.autor')),
                ('raw', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.proposicaoraw')),
            ],
            options={
                'ordering': ['-ano', '-numero'],
            },
        ),
    ]
