# Generated by Django 6.0.1 on 2026-03-24 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camara', '0001_initial'),
        ('legis', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proposicao',
            unique_together={('numero', 'ano', 'tipo')},
        ),
        migrations.AddField(
            model_name='autor',
            name='vereador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='camara.vereador'),
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='ano',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='numero',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='tipo',
            field=models.CharField(blank=True, choices=[('EM', 'Emenda'), ('EEP', 'Emenda Em Plenário'), ('IND', 'Indicação'), ('MO', 'Moção'), ('PDL', 'Projeto De Decreto Legislativo'), ('PDLC', 'Projeto De Lei Complementar'), ('PDL', 'Projeto De Lei'), ('PDR', 'Projeto De Resolução'), ('PECC', 'Proposta De Emenda à Constituição De Santa Catarina'), ('PECLO', 'Proposta De Emenda à Lei Orgânica'), ('RE', 'Recurso Regimental'), ('REQ', 'Requerimento'), ('REI', 'Requerimento De Informações Ao Executivo'), ('SG', 'Substitutivo Global')], max_length=80, null=True),
        ),
        migrations.CreateModel(
            name='ProposicaoComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio', models.DateField(blank=True, null=True)),
                ('comissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camara.comissao')),
                ('proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legis.proposicao')),
            ],
        ),
        migrations.CreateModel(
            name='Tramitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('situacao', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('orgao', models.CharField(blank=True, max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramitacoes', to='legis.proposicao')),
            ],
        ),
        migrations.CreateModel(
            name='Votacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('resultado', models.CharField(max_length=50)),
                ('proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legis.proposicao')),
            ],
        ),
        migrations.RemoveField(
            model_name='proposicao',
            name='autoria',
        ),
        migrations.RemoveField(
            model_name='proposicao',
            name='raw',
        ),
        migrations.RemoveField(
            model_name='proposicao',
            name='situacao',
        ),
        migrations.CreateModel(
            name='Autoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legis.autor')),
                ('tramitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legis.tramitacao')),
            ],
            options={
                'unique_together': {('tramitacao', 'autor')},
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.CharField(choices=[('favoravel', 'Favorável'), ('contrario', 'Contrário'), ('abstencao', 'Abstenção'), ('ausente_nao_justificado', 'Ausente Não Justificado'), ('ausente_justificado', 'Ausente Justificado'), ('presente_nao_votou', 'Presente Não Votou')], max_length=30)),
                ('vereador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camara.vereador')),
                ('votacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legis.votacao')),
            ],
            options={
                'unique_together': {('votacao', 'vereador')},
            },
        ),
    ]
