# Generated by Django 6.0.1 on 2026-03-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legis', '0002_alter_proposicao_unique_together_autor_vereador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposicao',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
