# Generated by Django 6.0.1 on 2026-03-24 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camara', '0004_vereador_data_desativacao'),
        ('legis', '0003_alter_proposicao_numero'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proposicao',
            new_name='Materia',
        ),
        migrations.RenameModel(
            old_name='ProposicaoComissao',
            new_name='MateriaComissao',
        ),
        migrations.RenameField(
            model_name='materiacomissao',
            old_name='proposicao',
            new_name='materia',
        ),
        migrations.RenameField(
            model_name='tramitacao',
            old_name='proposicao',
            new_name='materia',
        ),
        migrations.RenameField(
            model_name='votacao',
            old_name='proposicao',
            new_name='materia',
        ),
    ]
