# Generated by Django 6.0.1 on 2026-03-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legis', '0004_rename_proposicao_materia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='numero',
            field=models.IntegerField(blank=True, max_length=8, null=True),
        ),
    ]
