# Generated by Django 6.0.1 on 2026-03-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legis', '0005_alter_materia_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='ano',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
