# Generated by Django 6.0.1 on 2026-03-26 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0005_materiasettings_camara_id_and_more'),
        ('legis', '0006_alter_materia_ano_alter_materia_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='config',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materia', to='ingest.materiasettings'),
        ),
    ]
