# Generated by Django 6.0.1 on 2026-03-26 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camara', '0004_vereador_data_desativacao'),
        ('legis', '0007_materia_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoria',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camara.vereador'),
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
    ]
