# Generated by Django 6.0.1 on 2026-03-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legis', '0009_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='autores',
            field=models.ManyToManyField(related_name='materias', to='legis.autor'),
        ),
    ]
