# Generated by Django 6.0.1 on 2026-03-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legis', '0010_materia_autores'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='camara_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Atualizado na Câmara'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='data_apresentacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Apresentação'),
        ),
    ]
