# Generated by Django 6.0.1 on 2026-04-28 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0007_alter_materiahtml_arquivo_html_and_more'),
        ('legis', '0011_materia_camara_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='last_updated_sheet',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Atualizado no Sheets'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='config',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materia', to='ingest.materiasettings'),
        ),
    ]
