# Generated by Django 6.0.1 on 2026-04-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legis', '0012_materia_last_updated_sheet_alter_materia_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='assunto_by_ia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='assunto_by_ia_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Atualizado na IA'),
        ),
        migrations.AddField(
            model_name='materia',
            name='tema_by_ia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
