# Generated by Django 6.0.1 on 2026-04-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legis', '0013_materia_assunto_by_ia_materia_assunto_by_ia_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='eixo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='justifica_regiao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materia',
            name='palavras_chaves',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='participacao_publica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materia',
            name='regiao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
