# Generated by Django 6.0.1 on 2026-04-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legis', '0014_materia_eixo_materia_justifica_regiao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='assunto_by_ia_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Atualizado na IA'),
        ),
    ]
