# Generated by Django 6.0.1 on 2026-05-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legis', '0015_alter_materia_assunto_by_ia_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
