# Generated by Django 6.0.1 on 2026-04-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_perfil_cep_perfil_cidade_perfil_complemento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='date_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Aniversário'),
        ),
    ]
