# Generated by Django 6.0.1 on 2026-04-16 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_perfil_date_birth'),
        ('social', '0003_alter_perfil_date_birth_alter_perfil_numero'),
    ]

    operations = [
    ]
